"""criaçao da tabela task

Revision ID: 166bc71c2d2d
Revises: 6e88664b1705
Create Date: 2021-06-17 13:28:41.089595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166bc71c2d2d'
down_revision = '6e88664b1705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
