"""Criaçao da tabela categories

Revision ID: 60de4ef08327
Revises: 56a76463a3bf
Create Date: 2021-06-18 11:15:33.893155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60de4ef08327'
down_revision = '56a76463a3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
