"""criaçao do chave Fk eisenhower_id

Revision ID: 80f281f4d1e5
Revises: 166bc71c2d2d
Create Date: 2021-06-17 13:57:46.589885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f281f4d1e5'
down_revision = '166bc71c2d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('eisenhower_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'eisenhowers', ['eisenhower_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'eisenhower_id')
    # ### end Alembic commands ###
