"""Criaçao do campo importance tabela task

Revision ID: a05270dc68cf
Revises: 55e30da0d448
Create Date: 2021-06-18 15:02:12.254875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05270dc68cf'
down_revision = '55e30da0d448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('importance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'importance')
    # ### end Alembic commands ###
