"""Correçao do campo categoryy_id para category_id

Revision ID: ddb87cb35eca
Revises: a05270dc68cf
Create Date: 2021-06-18 16:35:06.602399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb87cb35eca'
down_revision = 'a05270dc68cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_categories', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('task_categories_categoryy_id_fkey', 'task_categories', type_='foreignkey')
    op.create_foreign_key(None, 'task_categories', 'categories', ['category_id'], ['id'])
    op.drop_column('task_categories', 'categoryy_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_categories', sa.Column('categoryy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task_categories', type_='foreignkey')
    op.create_foreign_key('task_categories_categoryy_id_fkey', 'task_categories', 'categories', ['categoryy_id'], ['id'])
    op.drop_column('task_categories', 'category_id')
    # ### end Alembic commands ###
